(cl:defpackage panda_gazebo-msg
  (:use )
  (:export
   "<BOUNDINGREGION>"
   "BOUNDINGREGION"
   "<FOLLOWJOINTTRAJECTORYACTION>"
   "FOLLOWJOINTTRAJECTORYACTION"
   "<FOLLOWJOINTTRAJECTORYACTIONFEEDBACK>"
   "FOLLOWJOINTTRAJECTORYACTIONFEEDBACK"
   "<FOLLOWJOINTTRAJECTORYACTIONGOAL>"
   "FOLLOWJOINTTRAJECTORYACTIONGOAL"
   "<FOLLOWJOINTTRAJECTORYACTIONRESULT>"
   "FOLLOWJOINTTRAJECTORYACTIONRESULT"
   "<FOLLOWJOINTTRAJECTORYFEEDBACK>"
   "FOLLOWJOINTTRAJECTORYFEEDBACK"
   "<FOLLOWJOINTTRAJECTORYGOAL>"
   "FOLLOWJOINTTRAJECTORYGOAL"
   "<FOLLOWJOINTTRAJECTORYRESULT>"
   "FOLLOWJOINTTRAJECTORYRESULT"
   "<JOINTLIMITS>"
   "JOINTLIMITS"
  ))

