// Generated by gencpp from file panda_gazebo/AddPlaneRequest.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_ADDPLANEREQUEST_H
#define PANDA_GAZEBO_MESSAGE_ADDPLANEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace panda_gazebo
{
template <class ContainerAllocator>
struct AddPlaneRequest_
{
  typedef AddPlaneRequest_<ContainerAllocator> Type;

  AddPlaneRequest_()
    : name()
    , frame_id()
    , pose()
    , normal()
    , offset(0.0)  {
      normal.assign(0.0);
  }
  AddPlaneRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , frame_id(_alloc)
    , pose(_alloc)
    , normal()
    , offset(0.0)  {
  (void)_alloc;
      normal.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef boost::array<double, 3>  _normal_type;
  _normal_type normal;

   typedef double _offset_type;
  _offset_type offset;





  typedef boost::shared_ptr< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddPlaneRequest_

typedef ::panda_gazebo::AddPlaneRequest_<std::allocator<void> > AddPlaneRequest;

typedef boost::shared_ptr< ::panda_gazebo::AddPlaneRequest > AddPlaneRequestPtr;
typedef boost::shared_ptr< ::panda_gazebo::AddPlaneRequest const> AddPlaneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.frame_id == rhs.frame_id &&
    lhs.pose == rhs.pose &&
    lhs.normal == rhs.normal &&
    lhs.offset == rhs.offset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4da7d01ed409a80fc9d1501b1293a08";
  }

  static const char* value(const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4da7d01ed409a80ULL;
  static const uint64_t static_value2 = 0xfc9d1501b1293a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/AddPlaneRequest";
  }

  static const char* value(const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service that can be used to add a plane to the planning scene.\n"
"string name\n"
"string frame_id\n"
"geometry_msgs/Pose pose\n"
"float64[3] normal\n"
"float64 offset  # In the direction of the normal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.frame_id);
      stream.next(m.pose);
      stream.next(m.normal);
      stream.next(m.offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddPlaneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::AddPlaneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::AddPlaneRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "normal[]" << std::endl;
    for (size_t i = 0; i < v.normal.size(); ++i)
    {
      s << indent << "  normal[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.normal[i]);
    }
    s << indent << "offset: ";
    Printer<double>::stream(s, indent + "  ", v.offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_ADDPLANEREQUEST_H
