// Generated by gencpp from file panda_gazebo/BoundingRegion.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_BOUNDINGREGION_H
#define PANDA_GAZEBO_MESSAGE_BOUNDINGREGION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_gazebo
{
template <class ContainerAllocator>
struct BoundingRegion_
{
  typedef BoundingRegion_<ContainerAllocator> Type;

  BoundingRegion_()
    : x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)  {
    }
  BoundingRegion_(const ContainerAllocator& _alloc)
    : x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)  {
  (void)_alloc;
    }



   typedef double _x_min_type;
  _x_min_type x_min;

   typedef double _x_max_type;
  _x_max_type x_max;

   typedef double _y_min_type;
  _y_min_type y_min;

   typedef double _y_max_type;
  _y_max_type y_max;

   typedef double _z_min_type;
  _z_min_type z_min;

   typedef double _z_max_type;
  _z_max_type z_max;





  typedef boost::shared_ptr< ::panda_gazebo::BoundingRegion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::BoundingRegion_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingRegion_

typedef ::panda_gazebo::BoundingRegion_<std::allocator<void> > BoundingRegion;

typedef boost::shared_ptr< ::panda_gazebo::BoundingRegion > BoundingRegionPtr;
typedef boost::shared_ptr< ::panda_gazebo::BoundingRegion const> BoundingRegionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::BoundingRegion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::BoundingRegion_<ContainerAllocator1> & lhs, const ::panda_gazebo::BoundingRegion_<ContainerAllocator2> & rhs)
{
  return lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max &&
    lhs.z_min == rhs.z_min &&
    lhs.z_max == rhs.z_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::BoundingRegion_<ContainerAllocator1> & lhs, const ::panda_gazebo::BoundingRegion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::BoundingRegion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::BoundingRegion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::BoundingRegion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad99bb284c3254d76796e1b66efe44bd";
  }

  static const char* value(const ::panda_gazebo::BoundingRegion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad99bb284c3254d7ULL;
  static const uint64_t static_value2 = 0x6796e1b66efe44bdULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/BoundingRegion";
  }

  static const char* value(const ::panda_gazebo::BoundingRegion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message used to define a bounding region by its min/max x,y z values.\n"
"float64 x_min\n"
"float64 x_max\n"
"float64 y_min\n"
"float64 y_max\n"
"float64 z_min\n"
"float64 z_max\n"
;
  }

  static const char* value(const ::panda_gazebo::BoundingRegion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_min);
      stream.next(m.x_max);
      stream.next(m.y_min);
      stream.next(m.y_max);
      stream.next(m.z_min);
      stream.next(m.z_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingRegion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::BoundingRegion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::BoundingRegion_<ContainerAllocator>& v)
  {
    s << indent << "x_min: ";
    Printer<double>::stream(s, indent + "  ", v.x_min);
    s << indent << "x_max: ";
    Printer<double>::stream(s, indent + "  ", v.x_max);
    s << indent << "y_min: ";
    Printer<double>::stream(s, indent + "  ", v.y_min);
    s << indent << "y_max: ";
    Printer<double>::stream(s, indent + "  ", v.y_max);
    s << indent << "z_min: ";
    Printer<double>::stream(s, indent + "  ", v.z_min);
    s << indent << "z_max: ";
    Printer<double>::stream(s, indent + "  ", v.z_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_BOUNDINGREGION_H
