// Generated by gencpp from file panda_gazebo/GetControlledJointsRequest.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETCONTROLLEDJOINTSREQUEST_H
#define PANDA_GAZEBO_MESSAGE_GETCONTROLLEDJOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetControlledJointsRequest_
{
  typedef GetControlledJointsRequest_<ContainerAllocator> Type;

  GetControlledJointsRequest_()
    : control_type()  {
    }
  GetControlledJointsRequest_(const ContainerAllocator& _alloc)
    : control_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _control_type_type;
  _control_type_type control_type;





  typedef boost::shared_ptr< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetControlledJointsRequest_

typedef ::panda_gazebo::GetControlledJointsRequest_<std::allocator<void> > GetControlledJointsRequest;

typedef boost::shared_ptr< ::panda_gazebo::GetControlledJointsRequest > GetControlledJointsRequestPtr;
typedef boost::shared_ptr< ::panda_gazebo::GetControlledJointsRequest const> GetControlledJointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.control_type == rhs.control_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ea89702d7e871352a5cee1adef402fd";
  }

  static const char* value(const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ea89702d7e87135ULL;
  static const uint64_t static_value2 = 0x2a5cee1adef402fdULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetControlledJointsRequest";
  }

  static const char* value(const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service that can be used to retrieve the joints that are controlled for a given\n"
"# control type.\n"
"string control_type\n"
;
  }

  static const char* value(const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetControlledJointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::GetControlledJointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "control_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.control_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETCONTROLLEDJOINTSREQUEST_H
