// Generated by gencpp from file panda_gazebo/GetControlledJoints.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETCONTROLLEDJOINTS_H
#define PANDA_GAZEBO_MESSAGE_GETCONTROLLEDJOINTS_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetControlledJointsRequest.h>
#include <panda_gazebo/GetControlledJointsResponse.h>


namespace panda_gazebo
{

struct GetControlledJoints
{

typedef GetControlledJointsRequest Request;
typedef GetControlledJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetControlledJoints
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetControlledJoints > {
  static const char* value()
  {
    return "c0fa937e297125af5ab96e86caa683cd";
  }

  static const char* value(const ::panda_gazebo::GetControlledJoints&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetControlledJoints > {
  static const char* value()
  {
    return "panda_gazebo/GetControlledJoints";
  }

  static const char* value(const ::panda_gazebo::GetControlledJoints&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetControlledJointsRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetControlledJoints >
template<>
struct MD5Sum< ::panda_gazebo::GetControlledJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetControlledJoints >::value();
  }
  static const char* value(const ::panda_gazebo::GetControlledJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetControlledJointsRequest> should match
// service_traits::DataType< ::panda_gazebo::GetControlledJoints >
template<>
struct DataType< ::panda_gazebo::GetControlledJointsRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetControlledJoints >::value();
  }
  static const char* value(const ::panda_gazebo::GetControlledJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetControlledJointsResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetControlledJoints >
template<>
struct MD5Sum< ::panda_gazebo::GetControlledJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetControlledJoints >::value();
  }
  static const char* value(const ::panda_gazebo::GetControlledJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetControlledJointsResponse> should match
// service_traits::DataType< ::panda_gazebo::GetControlledJoints >
template<>
struct DataType< ::panda_gazebo::GetControlledJointsResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetControlledJoints >::value();
  }
  static const char* value(const ::panda_gazebo::GetControlledJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETCONTROLLEDJOINTS_H
