// Generated by gencpp from file panda_gazebo/GetEeRpy.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEERPY_H
#define PANDA_GAZEBO_MESSAGE_GETEERPY_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetEeRpyRequest.h>
#include <panda_gazebo/GetEeRpyResponse.h>


namespace panda_gazebo
{

struct GetEeRpy
{

typedef GetEeRpyRequest Request;
typedef GetEeRpyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEeRpy
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetEeRpy > {
  static const char* value()
  {
    return "e0a899a2a3e84e53d60721d73970d6aa";
  }

  static const char* value(const ::panda_gazebo::GetEeRpy&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetEeRpy > {
  static const char* value()
  {
    return "panda_gazebo/GetEeRpy";
  }

  static const char* value(const ::panda_gazebo::GetEeRpy&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetEeRpyRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEeRpy >
template<>
struct MD5Sum< ::panda_gazebo::GetEeRpyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEeRpy >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeRpyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEeRpyRequest> should match
// service_traits::DataType< ::panda_gazebo::GetEeRpy >
template<>
struct DataType< ::panda_gazebo::GetEeRpyRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEeRpy >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeRpyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetEeRpyResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEeRpy >
template<>
struct MD5Sum< ::panda_gazebo::GetEeRpyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEeRpy >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeRpyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEeRpyResponse> should match
// service_traits::DataType< ::panda_gazebo::GetEeRpy >
template<>
struct DataType< ::panda_gazebo::GetEeRpyResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEeRpy >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeRpyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEERPY_H
