// Generated by gencpp from file panda_gazebo/GetEePose.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEEPOSE_H
#define PANDA_GAZEBO_MESSAGE_GETEEPOSE_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetEePoseRequest.h>
#include <panda_gazebo/GetEePoseResponse.h>


namespace panda_gazebo
{

struct GetEePose
{

typedef GetEePoseRequest Request;
typedef GetEePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEePose
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetEePose > {
  static const char* value()
  {
    return "37e6739d5ca462eb4146d24e3044b114";
  }

  static const char* value(const ::panda_gazebo::GetEePose&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetEePose > {
  static const char* value()
  {
    return "panda_gazebo/GetEePose";
  }

  static const char* value(const ::panda_gazebo::GetEePose&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetEePoseRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEePose >
template<>
struct MD5Sum< ::panda_gazebo::GetEePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEePoseRequest> should match
// service_traits::DataType< ::panda_gazebo::GetEePose >
template<>
struct DataType< ::panda_gazebo::GetEePoseRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetEePoseResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEePose >
template<>
struct MD5Sum< ::panda_gazebo::GetEePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEePoseResponse> should match
// service_traits::DataType< ::panda_gazebo::GetEePose >
template<>
struct DataType< ::panda_gazebo::GetEePoseResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEEPOSE_H
