// Generated by gencpp from file panda_gazebo/GetEePoseJointConfig.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEEPOSEJOINTCONFIG_H
#define PANDA_GAZEBO_MESSAGE_GETEEPOSEJOINTCONFIG_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetEePoseJointConfigRequest.h>
#include <panda_gazebo/GetEePoseJointConfigResponse.h>


namespace panda_gazebo
{

struct GetEePoseJointConfig
{

typedef GetEePoseJointConfigRequest Request;
typedef GetEePoseJointConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEePoseJointConfig
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetEePoseJointConfig > {
  static const char* value()
  {
    return "b9c46dcb95c6798588db6a317265add6";
  }

  static const char* value(const ::panda_gazebo::GetEePoseJointConfig&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetEePoseJointConfig > {
  static const char* value()
  {
    return "panda_gazebo/GetEePoseJointConfig";
  }

  static const char* value(const ::panda_gazebo::GetEePoseJointConfig&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetEePoseJointConfigRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEePoseJointConfig >
template<>
struct MD5Sum< ::panda_gazebo::GetEePoseJointConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEePoseJointConfig >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseJointConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEePoseJointConfigRequest> should match
// service_traits::DataType< ::panda_gazebo::GetEePoseJointConfig >
template<>
struct DataType< ::panda_gazebo::GetEePoseJointConfigRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEePoseJointConfig >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseJointConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetEePoseJointConfigResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEePoseJointConfig >
template<>
struct MD5Sum< ::panda_gazebo::GetEePoseJointConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEePoseJointConfig >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseJointConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEePoseJointConfigResponse> should match
// service_traits::DataType< ::panda_gazebo::GetEePoseJointConfig >
template<>
struct DataType< ::panda_gazebo::GetEePoseJointConfigResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEePoseJointConfig >::value();
  }
  static const char* value(const ::panda_gazebo::GetEePoseJointConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEEPOSEJOINTCONFIG_H
