// Generated by gencpp from file panda_gazebo/GetEePoseResponse.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEEPOSERESPONSE_H
#define PANDA_GAZEBO_MESSAGE_GETEEPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetEePoseResponse_
{
  typedef GetEePoseResponse_<ContainerAllocator> Type;

  GetEePoseResponse_()
    : pose()
    , success(false)
    , message()  {
    }
  GetEePoseResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEePoseResponse_

typedef ::panda_gazebo::GetEePoseResponse_<std::allocator<void> > GetEePoseResponse;

typedef boost::shared_ptr< ::panda_gazebo::GetEePoseResponse > GetEePoseResponsePtr;
typedef boost::shared_ptr< ::panda_gazebo::GetEePoseResponse const> GetEePoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37e6739d5ca462eb4146d24e3044b114";
  }

  static const char* value(const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37e6739d5ca462ebULL;
  static const uint64_t static_value2 = 0x4146d24e3044b114ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetEePoseResponse";
  }

  static const char* value(const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"bool success\n"
"string message\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEePoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetEePoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::GetEePoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEEPOSERESPONSE_H
