// Generated by gencpp from file panda_gazebo/GetEePoseJointConfigRequest.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEEPOSEJOINTCONFIGREQUEST_H
#define PANDA_GAZEBO_MESSAGE_GETEEPOSEJOINTCONFIGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetEePoseJointConfigRequest_
{
  typedef GetEePoseJointConfigRequest_<ContainerAllocator> Type;

  GetEePoseJointConfigRequest_()
    : pose()
    , attempts(0)  {
    }
  GetEePoseJointConfigRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , attempts(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef int32_t _attempts_type;
  _attempts_type attempts;





  typedef boost::shared_ptr< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetEePoseJointConfigRequest_

typedef ::panda_gazebo::GetEePoseJointConfigRequest_<std::allocator<void> > GetEePoseJointConfigRequest;

typedef boost::shared_ptr< ::panda_gazebo::GetEePoseJointConfigRequest > GetEePoseJointConfigRequestPtr;
typedef boost::shared_ptr< ::panda_gazebo::GetEePoseJointConfigRequest const> GetEePoseJointConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.attempts == rhs.attempts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef93b594913e8712347f7d1f63728586";
  }

  static const char* value(const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef93b594913e8712ULL;
  static const uint64_t static_value2 = 0x347f7d1f63728586ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetEePoseJointConfigRequest";
  }

  static const char* value(const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service that can be used to get a set of posible joint configuration for a given EE\n"
"# pose using MoveIt.\n"
"geometry_msgs/Pose pose\n"
"int32 attempts\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.attempts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEePoseJointConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::GetEePoseJointConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "attempts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.attempts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEEPOSEJOINTCONFIGREQUEST_H
