// Generated by gencpp from file panda_gazebo/GetEe.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEE_H
#define PANDA_GAZEBO_MESSAGE_GETEE_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetEeRequest.h>
#include <panda_gazebo/GetEeResponse.h>


namespace panda_gazebo
{

struct GetEe
{

typedef GetEeRequest Request;
typedef GetEeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEe
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetEe > {
  static const char* value()
  {
    return "0d38e7dfd196a6d5a64530f17deabb47";
  }

  static const char* value(const ::panda_gazebo::GetEe&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetEe > {
  static const char* value()
  {
    return "panda_gazebo/GetEe";
  }

  static const char* value(const ::panda_gazebo::GetEe&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetEeRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEe >
template<>
struct MD5Sum< ::panda_gazebo::GetEeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEe >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEeRequest> should match
// service_traits::DataType< ::panda_gazebo::GetEe >
template<>
struct DataType< ::panda_gazebo::GetEeRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEe >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetEeResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetEe >
template<>
struct MD5Sum< ::panda_gazebo::GetEeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetEe >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetEeResponse> should match
// service_traits::DataType< ::panda_gazebo::GetEe >
template<>
struct DataType< ::panda_gazebo::GetEeResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetEe >::value();
  }
  static const char* value(const ::panda_gazebo::GetEeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEE_H
