// Generated by gencpp from file panda_gazebo/GetEeResponse.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETEERESPONSE_H
#define PANDA_GAZEBO_MESSAGE_GETEERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetEeResponse_
{
  typedef GetEeResponse_<ContainerAllocator> Type;

  GetEeResponse_()
    : ee_name()
    , success(false)
    , message()  {
    }
  GetEeResponse_(const ContainerAllocator& _alloc)
    : ee_name(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ee_name_type;
  _ee_name_type ee_name;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::panda_gazebo::GetEeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetEeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEeResponse_

typedef ::panda_gazebo::GetEeResponse_<std::allocator<void> > GetEeResponse;

typedef boost::shared_ptr< ::panda_gazebo::GetEeResponse > GetEeResponsePtr;
typedef boost::shared_ptr< ::panda_gazebo::GetEeResponse const> GetEeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetEeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::GetEeResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetEeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ee_name == rhs.ee_name &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::GetEeResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetEeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetEeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetEeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetEeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d38e7dfd196a6d5a64530f17deabb47";
  }

  static const char* value(const ::panda_gazebo::GetEeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d38e7dfd196a6d5ULL;
  static const uint64_t static_value2 = 0xa64530f17deabb47ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetEeResponse";
  }

  static const char* value(const ::panda_gazebo::GetEeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ee_name\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::panda_gazebo::GetEeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ee_name);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetEeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::GetEeResponse_<ContainerAllocator>& v)
  {
    s << indent << "ee_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ee_name);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETEERESPONSE_H
