// Generated by gencpp from file panda_gazebo/GetMoveItControlledJointsRequest.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETMOVEITCONTROLLEDJOINTSREQUEST_H
#define PANDA_GAZEBO_MESSAGE_GETMOVEITCONTROLLEDJOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetMoveItControlledJointsRequest_
{
  typedef GetMoveItControlledJointsRequest_<ContainerAllocator> Type;

  GetMoveItControlledJointsRequest_()
    {
    }
  GetMoveItControlledJointsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMoveItControlledJointsRequest_

typedef ::panda_gazebo::GetMoveItControlledJointsRequest_<std::allocator<void> > GetMoveItControlledJointsRequest;

typedef boost::shared_ptr< ::panda_gazebo::GetMoveItControlledJointsRequest > GetMoveItControlledJointsRequestPtr;
typedef boost::shared_ptr< ::panda_gazebo::GetMoveItControlledJointsRequest const> GetMoveItControlledJointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetMoveItControlledJointsRequest";
  }

  static const char* value(const ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service that can be used to retrieve the joints that are currently controlled by MoveIt.\n"
;
  }

  static const char* value(const ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMoveItControlledJointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::panda_gazebo::GetMoveItControlledJointsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETMOVEITCONTROLLEDJOINTSREQUEST_H
