// Generated by gencpp from file panda_gazebo/GetRandomEePose.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETRANDOMEEPOSE_H
#define PANDA_GAZEBO_MESSAGE_GETRANDOMEEPOSE_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetRandomEePoseRequest.h>
#include <panda_gazebo/GetRandomEePoseResponse.h>


namespace panda_gazebo
{

struct GetRandomEePose
{

typedef GetRandomEePoseRequest Request;
typedef GetRandomEePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRandomEePose
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetRandomEePose > {
  static const char* value()
  {
    return "d52fb2aef180d014e1bace1ad112db90";
  }

  static const char* value(const ::panda_gazebo::GetRandomEePose&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetRandomEePose > {
  static const char* value()
  {
    return "panda_gazebo/GetRandomEePose";
  }

  static const char* value(const ::panda_gazebo::GetRandomEePose&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetRandomEePoseRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetRandomEePose >
template<>
struct MD5Sum< ::panda_gazebo::GetRandomEePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetRandomEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomEePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetRandomEePoseRequest> should match
// service_traits::DataType< ::panda_gazebo::GetRandomEePose >
template<>
struct DataType< ::panda_gazebo::GetRandomEePoseRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetRandomEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomEePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetRandomEePoseResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetRandomEePose >
template<>
struct MD5Sum< ::panda_gazebo::GetRandomEePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetRandomEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomEePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetRandomEePoseResponse> should match
// service_traits::DataType< ::panda_gazebo::GetRandomEePose >
template<>
struct DataType< ::panda_gazebo::GetRandomEePoseResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetRandomEePose >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomEePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETRANDOMEEPOSE_H
