// Generated by gencpp from file panda_gazebo/GetRandomJointPositionsResponse.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETRANDOMJOINTPOSITIONSRESPONSE_H
#define PANDA_GAZEBO_MESSAGE_GETRANDOMJOINTPOSITIONSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetRandomJointPositionsResponse_
{
  typedef GetRandomJointPositionsResponse_<ContainerAllocator> Type;

  GetRandomJointPositionsResponse_()
    : joint_names()
    , joint_positions()
    , success(false)
    , message()  {
    }
  GetRandomJointPositionsResponse_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , joint_positions(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRandomJointPositionsResponse_

typedef ::panda_gazebo::GetRandomJointPositionsResponse_<std::allocator<void> > GetRandomJointPositionsResponse;

typedef boost::shared_ptr< ::panda_gazebo::GetRandomJointPositionsResponse > GetRandomJointPositionsResponsePtr;
typedef boost::shared_ptr< ::panda_gazebo::GetRandomJointPositionsResponse const> GetRandomJointPositionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.joint_positions == rhs.joint_positions &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c2af30b0f98c15bbeb4220c5da17d05";
  }

  static const char* value(const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c2af30b0f98c15bULL;
  static const uint64_t static_value2 = 0xbeb4220c5da17d05ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetRandomJointPositionsResponse";
  }

  static const char* value(const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] joint_names\n"
"float64[] joint_positions\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.joint_positions);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRandomJointPositionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::GetRandomJointPositionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETRANDOMJOINTPOSITIONSRESPONSE_H
