// Generated by gencpp from file panda_gazebo/GetRandomEePoseResponse.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETRANDOMEEPOSERESPONSE_H
#define PANDA_GAZEBO_MESSAGE_GETRANDOMEEPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace panda_gazebo
{
template <class ContainerAllocator>
struct GetRandomEePoseResponse_
{
  typedef GetRandomEePoseResponse_<ContainerAllocator> Type;

  GetRandomEePoseResponse_()
    : ee_pose()
    , joint_names()
    , joint_positions()
    , success(false)
    , message()  {
    }
  GetRandomEePoseResponse_(const ContainerAllocator& _alloc)
    : ee_pose(_alloc)
    , joint_names(_alloc)
    , joint_positions(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _ee_pose_type;
  _ee_pose_type ee_pose;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRandomEePoseResponse_

typedef ::panda_gazebo::GetRandomEePoseResponse_<std::allocator<void> > GetRandomEePoseResponse;

typedef boost::shared_ptr< ::panda_gazebo::GetRandomEePoseResponse > GetRandomEePoseResponsePtr;
typedef boost::shared_ptr< ::panda_gazebo::GetRandomEePoseResponse const> GetRandomEePoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ee_pose == rhs.ee_pose &&
    lhs.joint_names == rhs.joint_names &&
    lhs.joint_positions == rhs.joint_positions &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator1> & lhs, const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3516fb5b6d6e148286f2b7522e25070a";
  }

  static const char* value(const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3516fb5b6d6e1482ULL;
  static const uint64_t static_value2 = 0x86f2b7522e25070aULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/GetRandomEePoseResponse";
  }

  static const char* value(const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose ee_pose\n"
"string[] joint_names\n"
"float64[] joint_positions\n"
"bool success\n"
"string message\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ee_pose);
      stream.next(m.joint_names);
      stream.next(m.joint_positions);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRandomEePoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::GetRandomEePoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "ee_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.ee_pose);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETRANDOMEEPOSERESPONSE_H
