// Generated by gencpp from file panda_gazebo/GetRandomJointPositions.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_GETRANDOMJOINTPOSITIONS_H
#define PANDA_GAZEBO_MESSAGE_GETRANDOMJOINTPOSITIONS_H

#include <ros/service_traits.h>


#include <panda_gazebo/GetRandomJointPositionsRequest.h>
#include <panda_gazebo/GetRandomJointPositionsResponse.h>


namespace panda_gazebo
{

struct GetRandomJointPositions
{

typedef GetRandomJointPositionsRequest Request;
typedef GetRandomJointPositionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRandomJointPositions
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::GetRandomJointPositions > {
  static const char* value()
  {
    return "4d6e6a8cd1ba93ef030177ed39cffd53";
  }

  static const char* value(const ::panda_gazebo::GetRandomJointPositions&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::GetRandomJointPositions > {
  static const char* value()
  {
    return "panda_gazebo/GetRandomJointPositions";
  }

  static const char* value(const ::panda_gazebo::GetRandomJointPositions&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::GetRandomJointPositionsRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::GetRandomJointPositions >
template<>
struct MD5Sum< ::panda_gazebo::GetRandomJointPositionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetRandomJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetRandomJointPositionsRequest> should match
// service_traits::DataType< ::panda_gazebo::GetRandomJointPositions >
template<>
struct DataType< ::panda_gazebo::GetRandomJointPositionsRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetRandomJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::GetRandomJointPositionsResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::GetRandomJointPositions >
template<>
struct MD5Sum< ::panda_gazebo::GetRandomJointPositionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::GetRandomJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomJointPositionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::GetRandomJointPositionsResponse> should match
// service_traits::DataType< ::panda_gazebo::GetRandomJointPositions >
template<>
struct DataType< ::panda_gazebo::GetRandomJointPositionsResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::GetRandomJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::GetRandomJointPositionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_GETRANDOMJOINTPOSITIONS_H
