//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the panda_gazebo package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __panda_gazebo__JOINTPOSITIONSCONFIG_H__
#define __panda_gazebo__JOINTPOSITIONSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace panda_gazebo
{
  class JointPositionsConfigStatics;

  class JointPositionsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(JointPositionsConfig &config, const JointPositionsConfig &max, const JointPositionsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const JointPositionsConfig &config1, const JointPositionsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, JointPositionsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const JointPositionsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, JointPositionsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const JointPositionsConfig &config) const = 0;
      virtual void getValue(const JointPositionsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T JointPositionsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T JointPositionsConfig::* field;

      virtual void clamp(JointPositionsConfig &config, const JointPositionsConfig &max, const JointPositionsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const JointPositionsConfig &config1, const JointPositionsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, JointPositionsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const JointPositionsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, JointPositionsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const JointPositionsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const JointPositionsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, JointPositionsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, JointPositionsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<JointPositionsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(JointPositionsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class ARM
{
  public:
    ARM()
    {
      state = true;
      name = "arm";
    }

    void setParams(JointPositionsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("joint1_position"==(*_i)->name){joint1_position = boost::any_cast<double>(val);}
        if("joint2_position"==(*_i)->name){joint2_position = boost::any_cast<double>(val);}
        if("joint3_position"==(*_i)->name){joint3_position = boost::any_cast<double>(val);}
        if("joint4_position"==(*_i)->name){joint4_position = boost::any_cast<double>(val);}
        if("joint5_position"==(*_i)->name){joint5_position = boost::any_cast<double>(val);}
        if("joint6_position"==(*_i)->name){joint6_position = boost::any_cast<double>(val);}
        if("joint7_position"==(*_i)->name){joint7_position = boost::any_cast<double>(val);}
      }
    }

    double joint1_position;
double joint2_position;
double joint3_position;
double joint4_position;
double joint5_position;
double joint6_position;
double joint7_position;

    bool state;
    std::string name;

    
}arm;

class HAND
{
  public:
    HAND()
    {
      state = true;
      name = "hand";
    }

    void setParams(JointPositionsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("width"==(*_i)->name){width = boost::any_cast<double>(val);}
        if("speed"==(*_i)->name){speed = boost::any_cast<double>(val);}
      }
    }

    double width;
double speed;

    bool state;
    std::string name;

    
}hand;

}groups;



//#line 12 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint1_position;
//#line 13 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint2_position;
//#line 14 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint3_position;
//#line 15 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint4_position;
//#line 16 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint5_position;
//#line 17 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint6_position;
//#line 18 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double joint7_position;
//#line 22 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double width;
//#line 31 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      double speed;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("JointPositionsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const JointPositionsConfig &__max__ = __getMax__();
      const JointPositionsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const JointPositionsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const JointPositionsConfig &__getDefault__();
    static const JointPositionsConfig &__getMax__();
    static const JointPositionsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const JointPositionsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void JointPositionsConfig::ParamDescription<std::string>::clamp(JointPositionsConfig &config, const JointPositionsConfig &max, const JointPositionsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class JointPositionsConfigStatics
  {
    friend class JointPositionsConfig;

    JointPositionsConfigStatics()
    {
JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT, JointPositionsConfig> Default("Default", "", 0, 0, true, &JointPositionsConfig::groups);
JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT::ARM, JointPositionsConfig::DEFAULT> arm("arm", "", 0, 1, true, &JointPositionsConfig::DEFAULT::arm);
//#line 12 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint1_position = -2.8973;
//#line 12 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint1_position = 2.8973;
//#line 12 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint1_position = 0.0;
//#line 12 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint1_position", "double", 0, "Joint 1 position control command", "", &JointPositionsConfig::joint1_position)));
//#line 12 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint1_position", "double", 0, "Joint 1 position control command", "", &JointPositionsConfig::joint1_position)));
//#line 13 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint2_position = -1.7628;
//#line 13 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint2_position = 1.7628;
//#line 13 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint2_position = 0.0;
//#line 13 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint2_position", "double", 1, "Joint 2 position control command", "", &JointPositionsConfig::joint2_position)));
//#line 13 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint2_position", "double", 1, "Joint 2 position control command", "", &JointPositionsConfig::joint2_position)));
//#line 14 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint3_position = -2.8973;
//#line 14 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint3_position = 2.8973;
//#line 14 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint3_position = 0.0;
//#line 14 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint3_position", "double", 2, "Joint 3 position control command", "", &JointPositionsConfig::joint3_position)));
//#line 14 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint3_position", "double", 2, "Joint 3 position control command", "", &JointPositionsConfig::joint3_position)));
//#line 15 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint4_position = -3.0718;
//#line 15 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint4_position = -0.0698;
//#line 15 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint4_position = 0.0;
//#line 15 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint4_position", "double", 3, "Joint 4 position control command", "", &JointPositionsConfig::joint4_position)));
//#line 15 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint4_position", "double", 3, "Joint 4 position control command", "", &JointPositionsConfig::joint4_position)));
//#line 16 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint5_position = -2.8973;
//#line 16 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint5_position = 2.8973;
//#line 16 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint5_position = 0.0;
//#line 16 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint5_position", "double", 4, "Joint 5 position control command", "", &JointPositionsConfig::joint5_position)));
//#line 16 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint5_position", "double", 4, "Joint 5 position control command", "", &JointPositionsConfig::joint5_position)));
//#line 17 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint6_position = -0.0175;
//#line 17 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint6_position = 3.7525;
//#line 17 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint6_position = 0.0;
//#line 17 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint6_position", "double", 5, "Joint 6 position control command", "", &JointPositionsConfig::joint6_position)));
//#line 17 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint6_position", "double", 5, "Joint 6 position control command", "", &JointPositionsConfig::joint6_position)));
//#line 18 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.joint7_position = -2.8973;
//#line 18 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.joint7_position = 2.8973;
//#line 18 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.joint7_position = 0.0;
//#line 18 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      arm.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint7_position", "double", 6, "Joint 7 position control command", "", &JointPositionsConfig::joint7_position)));
//#line 18 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("joint7_position", "double", 6, "Joint 7 position control command", "", &JointPositionsConfig::joint7_position)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      arm.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(JointPositionsConfig::AbstractGroupDescriptionConstPtr(new JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT::ARM, JointPositionsConfig::DEFAULT>(arm)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(JointPositionsConfig::AbstractGroupDescriptionConstPtr(new JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT::ARM, JointPositionsConfig::DEFAULT>(arm)));
JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT::HAND, JointPositionsConfig::DEFAULT> hand("hand", "", 0, 2, true, &JointPositionsConfig::DEFAULT::hand);
//#line 22 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.width = 0.0;
//#line 22 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.width = 0.08;
//#line 22 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.width = 0.0;
//#line 22 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      hand.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("width", "double", 7, "Gripper width", "", &JointPositionsConfig::width)));
//#line 22 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("width", "double", 7, "Gripper width", "", &JointPositionsConfig::width)));
//#line 31 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __min__.speed = 0.0;
//#line 31 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __max__.speed = 0.2;
//#line 31 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __default__.speed = 0.2;
//#line 31 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      hand.abstract_parameters.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("speed", "double", 8, "Gripper speed", "", &JointPositionsConfig::speed)));
//#line 31 "/workspaces/ros-gazebo-gym-ws/src/rosdeps/panda_gazebo/panda_gazebo/cfg/dyn_reconf/PositionControlTestDynReconf.cfg"
      __param_descriptions__.push_back(JointPositionsConfig::AbstractParamDescriptionConstPtr(new JointPositionsConfig::ParamDescription<double>("speed", "double", 8, "Gripper speed", "", &JointPositionsConfig::speed)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      hand.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(JointPositionsConfig::AbstractGroupDescriptionConstPtr(new JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT::HAND, JointPositionsConfig::DEFAULT>(hand)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(JointPositionsConfig::AbstractGroupDescriptionConstPtr(new JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT::HAND, JointPositionsConfig::DEFAULT>(hand)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(JointPositionsConfig::AbstractGroupDescriptionConstPtr(new JointPositionsConfig::GroupDescription<JointPositionsConfig::DEFAULT, JointPositionsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<JointPositionsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<JointPositionsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<JointPositionsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    JointPositionsConfig __max__;
    JointPositionsConfig __min__;
    JointPositionsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const JointPositionsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static JointPositionsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &JointPositionsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const JointPositionsConfig &JointPositionsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const JointPositionsConfig &JointPositionsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const JointPositionsConfig &JointPositionsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<JointPositionsConfig::AbstractParamDescriptionConstPtr> &JointPositionsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<JointPositionsConfig::AbstractGroupDescriptionConstPtr> &JointPositionsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const JointPositionsConfigStatics *JointPositionsConfig::__get_statics__()
  {
    const static JointPositionsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = JointPositionsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __JOINTPOSITIONSRECONFIGURATOR_H__
