// Generated by gencpp from file panda_gazebo/LockJoints.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_LOCKJOINTS_H
#define PANDA_GAZEBO_MESSAGE_LOCKJOINTS_H

#include <ros/service_traits.h>


#include <panda_gazebo/LockJointsRequest.h>
#include <panda_gazebo/LockJointsResponse.h>


namespace panda_gazebo
{

struct LockJoints
{

typedef LockJointsRequest Request;
typedef LockJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LockJoints
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::LockJoints > {
  static const char* value()
  {
    return "c5f1ee92ccf62d5afc6116cb756e3854";
  }

  static const char* value(const ::panda_gazebo::LockJoints&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::LockJoints > {
  static const char* value()
  {
    return "panda_gazebo/LockJoints";
  }

  static const char* value(const ::panda_gazebo::LockJoints&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::LockJointsRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::LockJoints >
template<>
struct MD5Sum< ::panda_gazebo::LockJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::LockJoints >::value();
  }
  static const char* value(const ::panda_gazebo::LockJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::LockJointsRequest> should match
// service_traits::DataType< ::panda_gazebo::LockJoints >
template<>
struct DataType< ::panda_gazebo::LockJointsRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::LockJoints >::value();
  }
  static const char* value(const ::panda_gazebo::LockJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::LockJointsResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::LockJoints >
template<>
struct MD5Sum< ::panda_gazebo::LockJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::LockJoints >::value();
  }
  static const char* value(const ::panda_gazebo::LockJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::LockJointsResponse> should match
// service_traits::DataType< ::panda_gazebo::LockJoints >
template<>
struct DataType< ::panda_gazebo::LockJointsResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::LockJoints >::value();
  }
  static const char* value(const ::panda_gazebo::LockJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_LOCKJOINTS_H
