// Generated by gencpp from file panda_gazebo/SetEe.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_SETEE_H
#define PANDA_GAZEBO_MESSAGE_SETEE_H

#include <ros/service_traits.h>


#include <panda_gazebo/SetEeRequest.h>
#include <panda_gazebo/SetEeResponse.h>


namespace panda_gazebo
{

struct SetEe
{

typedef SetEeRequest Request;
typedef SetEeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEe
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::SetEe > {
  static const char* value()
  {
    return "9966df81bf9b15c45e8f850d588fc889";
  }

  static const char* value(const ::panda_gazebo::SetEe&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::SetEe > {
  static const char* value()
  {
    return "panda_gazebo/SetEe";
  }

  static const char* value(const ::panda_gazebo::SetEe&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::SetEeRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::SetEe >
template<>
struct MD5Sum< ::panda_gazebo::SetEeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetEe >::value();
  }
  static const char* value(const ::panda_gazebo::SetEeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetEeRequest> should match
// service_traits::DataType< ::panda_gazebo::SetEe >
template<>
struct DataType< ::panda_gazebo::SetEeRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetEe >::value();
  }
  static const char* value(const ::panda_gazebo::SetEeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::SetEeResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::SetEe >
template<>
struct MD5Sum< ::panda_gazebo::SetEeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetEe >::value();
  }
  static const char* value(const ::panda_gazebo::SetEeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetEeResponse> should match
// service_traits::DataType< ::panda_gazebo::SetEe >
template<>
struct DataType< ::panda_gazebo::SetEeResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetEe >::value();
  }
  static const char* value(const ::panda_gazebo::SetEeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_SETEE_H
