// Generated by gencpp from file panda_gazebo/SetEePose.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_SETEEPOSE_H
#define PANDA_GAZEBO_MESSAGE_SETEEPOSE_H

#include <ros/service_traits.h>


#include <panda_gazebo/SetEePoseRequest.h>
#include <panda_gazebo/SetEePoseResponse.h>


namespace panda_gazebo
{

struct SetEePose
{

typedef SetEePoseRequest Request;
typedef SetEePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEePose
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::SetEePose > {
  static const char* value()
  {
    return "28e4dd667b29bd35b516ba1d379b7529";
  }

  static const char* value(const ::panda_gazebo::SetEePose&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::SetEePose > {
  static const char* value()
  {
    return "panda_gazebo/SetEePose";
  }

  static const char* value(const ::panda_gazebo::SetEePose&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::SetEePoseRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::SetEePose >
template<>
struct MD5Sum< ::panda_gazebo::SetEePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::SetEePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetEePoseRequest> should match
// service_traits::DataType< ::panda_gazebo::SetEePose >
template<>
struct DataType< ::panda_gazebo::SetEePoseRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::SetEePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::SetEePoseResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::SetEePose >
template<>
struct MD5Sum< ::panda_gazebo::SetEePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::SetEePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetEePoseResponse> should match
// service_traits::DataType< ::panda_gazebo::SetEePose >
template<>
struct DataType< ::panda_gazebo::SetEePoseResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetEePose >::value();
  }
  static const char* value(const ::panda_gazebo::SetEePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_SETEEPOSE_H
