// Generated by gencpp from file panda_gazebo/SetJointPositions.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_SETJOINTPOSITIONS_H
#define PANDA_GAZEBO_MESSAGE_SETJOINTPOSITIONS_H

#include <ros/service_traits.h>


#include <panda_gazebo/SetJointPositionsRequest.h>
#include <panda_gazebo/SetJointPositionsResponse.h>


namespace panda_gazebo
{

struct SetJointPositions
{

typedef SetJointPositionsRequest Request;
typedef SetJointPositionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointPositions
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::SetJointPositions > {
  static const char* value()
  {
    return "7116eda9a72658a9c8b658ed0557ca6f";
  }

  static const char* value(const ::panda_gazebo::SetJointPositions&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::SetJointPositions > {
  static const char* value()
  {
    return "panda_gazebo/SetJointPositions";
  }

  static const char* value(const ::panda_gazebo::SetJointPositions&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::SetJointPositionsRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::SetJointPositions >
template<>
struct MD5Sum< ::panda_gazebo::SetJointPositionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetJointPositionsRequest> should match
// service_traits::DataType< ::panda_gazebo::SetJointPositions >
template<>
struct DataType< ::panda_gazebo::SetJointPositionsRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::SetJointPositionsResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::SetJointPositions >
template<>
struct MD5Sum< ::panda_gazebo::SetJointPositionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointPositionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetJointPositionsResponse> should match
// service_traits::DataType< ::panda_gazebo::SetJointPositions >
template<>
struct DataType< ::panda_gazebo::SetJointPositionsResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetJointPositions >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointPositionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_SETJOINTPOSITIONS_H
