// Generated by gencpp from file panda_gazebo/SetJointPositionsRequest.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_SETJOINTPOSITIONSREQUEST_H
#define PANDA_GAZEBO_MESSAGE_SETJOINTPOSITIONSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_gazebo
{
template <class ContainerAllocator>
struct SetJointPositionsRequest_
{
  typedef SetJointPositionsRequest_<ContainerAllocator> Type;

  SetJointPositionsRequest_()
    : joint_names()
    , joint_positions()
    , wait(false)  {
    }
  SetJointPositionsRequest_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , joint_positions(_alloc)
    , wait(false)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef uint8_t _wait_type;
  _wait_type wait;





  typedef boost::shared_ptr< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointPositionsRequest_

typedef ::panda_gazebo::SetJointPositionsRequest_<std::allocator<void> > SetJointPositionsRequest;

typedef boost::shared_ptr< ::panda_gazebo::SetJointPositionsRequest > SetJointPositionsRequestPtr;
typedef boost::shared_ptr< ::panda_gazebo::SetJointPositionsRequest const> SetJointPositionsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.joint_positions == rhs.joint_positions &&
    lhs.wait == rhs.wait;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator1> & lhs, const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39dd72f0b60217b748318b9f8bd2fbff";
  }

  static const char* value(const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39dd72f0b60217b7ULL;
  static const uint64_t static_value2 = 0x48318b9f8bd2fbffULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_gazebo/SetJointPositionsRequest";
  }

  static const char* value(const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service that can be used to control the robot joint positions using the\n"
"# panda_control_server.\n"
"# NOTE: This is done by publishing the joint efforts commands to the right topics.\n"
"string[] joint_names\n"
"float64[] joint_positions\n"
"bool wait\n"
;
  }

  static const char* value(const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.joint_positions);
      stream.next(m.wait);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointPositionsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_gazebo::SetJointPositionsRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "wait: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_SETJOINTPOSITIONSREQUEST_H
