// Generated by gencpp from file panda_gazebo/SetJointCommands.msg
// DO NOT EDIT!


#ifndef PANDA_GAZEBO_MESSAGE_SETJOINTCOMMANDS_H
#define PANDA_GAZEBO_MESSAGE_SETJOINTCOMMANDS_H

#include <ros/service_traits.h>


#include <panda_gazebo/SetJointCommandsRequest.h>
#include <panda_gazebo/SetJointCommandsResponse.h>


namespace panda_gazebo
{

struct SetJointCommands
{

typedef SetJointCommandsRequest Request;
typedef SetJointCommandsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointCommands
} // namespace panda_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_gazebo::SetJointCommands > {
  static const char* value()
  {
    return "e45f98ce30463e2aa1e33dd48f97b157";
  }

  static const char* value(const ::panda_gazebo::SetJointCommands&) { return value(); }
};

template<>
struct DataType< ::panda_gazebo::SetJointCommands > {
  static const char* value()
  {
    return "panda_gazebo/SetJointCommands";
  }

  static const char* value(const ::panda_gazebo::SetJointCommands&) { return value(); }
};


// service_traits::MD5Sum< ::panda_gazebo::SetJointCommandsRequest> should match
// service_traits::MD5Sum< ::panda_gazebo::SetJointCommands >
template<>
struct MD5Sum< ::panda_gazebo::SetJointCommandsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetJointCommands >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointCommandsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetJointCommandsRequest> should match
// service_traits::DataType< ::panda_gazebo::SetJointCommands >
template<>
struct DataType< ::panda_gazebo::SetJointCommandsRequest>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetJointCommands >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointCommandsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_gazebo::SetJointCommandsResponse> should match
// service_traits::MD5Sum< ::panda_gazebo::SetJointCommands >
template<>
struct MD5Sum< ::panda_gazebo::SetJointCommandsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_gazebo::SetJointCommands >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointCommandsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_gazebo::SetJointCommandsResponse> should match
// service_traits::DataType< ::panda_gazebo::SetJointCommands >
template<>
struct DataType< ::panda_gazebo::SetJointCommandsResponse>
{
  static const char* value()
  {
    return DataType< ::panda_gazebo::SetJointCommands >::value();
  }
  static const char* value(const ::panda_gazebo::SetJointCommandsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_GAZEBO_MESSAGE_SETJOINTCOMMANDS_H
